/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.javascript.tests;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.TopLevel;

/**
 * A script with enough small functions to overflow a single generated class file's constant pool
 * must still compile with the optimizing compiler, by splitting the generated bytecode across more
 * than one class file, rather than falling all the way back to the interpreter for the whole
 * script.
 *
 * <p>The functions are nested a few hundred at a time inside outer wrapper functions (rather than
 * all being declared flat, directly in the top-level script) so that no single body method - in
 * particular the outer scope's own body method, which has to emit "hoist this nested function" code
 * for each of its direct children - comes anywhere near the unrelated 64K-bytecode-per-method
 * limit. Only the aggregate constant pool, shared by every function's body method before splitting
 * kicks in, is meant to overflow here.
 */
public class ClassFileSplittingTest {
    private Context cx;
    private TopLevel scope;

    @BeforeEach
    public void setUp() {
        cx = Context.enter();
        scope = cx.initStandardObjects();
    }

    @AfterEach
    public void tearDown() {
        Context.exit();
    }

    @Test
    public void manyFunctionsOverflowingConstantPoolStillCompileAndRun() {
        int outerCount = 220;
        int innerCount = 220;
        StringBuilder src = new StringBuilder();
        for (int o = 0; o != outerCount; ++o) {
            src.append("function outer").append(o).append("() {\n");
            for (int i = 0; i != innerCount; ++i) {
                src.append("  function inner")
                        .append(o)
                        .append('_')
                        .append(i)
                        .append("() { return 'literal_")
                        .append(o)
                        .append('_')
                        .append(i)
                        .append("'; }\n");
            }
            src.append("  return inner").append(o).append("_0();\n");
            src.append("}\n");
        }
        src.append("outer0() + '|' + outer1() + '|' + outer")
                .append(outerCount - 1)
                .append("();\n");

        Object result = cx.evaluateString(scope, src.toString(), "big.js", 1, null);

        assertEquals("literal_0_0|literal_1_0|literal_" + (outerCount - 1) + "_0", result);
    }
}
