/* -*- Mode: java; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.javascript.optimizer;

import org.mozilla.javascript.Context;
import org.mozilla.javascript.ScriptRuntime;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.Wrapper;

import java.lang.invoke.CallSite;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodHandles.Lookup;
import java.lang.invoke.MethodType;
import java.lang.invoke.MutableCallSite;

/**
 * This class contains methods that are called by generated bytecode that
 * sets up and uses the InvokeDynamic instruction.
 */

public class InvokeDynamicSupport {

    static class CachingCallSite extends MutableCallSite {
        final Lookup lookup;

        CachingCallSite(Lookup lookup, MethodType type) {
            super(type);
            this.lookup = lookup;
        }
    }

    /*
    public static CallSite bootstrapProp0Call(MethodHandles.Lookup lookup,
                                              String name, MethodType type) {
        CachingCallSite callSite = new CachingCallSite(lookup, type);
        MethodHandle check = INITCALL.bindTo(callSite);
        check = check.asType(type);

        callSite.setTarget(check);
        return callSite;
    }
    */

    /**
     * Begin the process of setting up a CallSite to get the property of an object.
     */
    @SuppressWarnings("unused")
    public static CallSite bootstrapGetObjectProp(MethodHandles.Lookup lookup,
                                                  String name, MethodType type) {
        CachingCallSite callSite = new CachingCallSite(lookup, type);
        // The first call will be to getObjectProp in this class.
        MethodHandle check = INITGETOBJPROP.bindTo(callSite);
        check = check.asType(type);

        callSite.setTarget(check);
        return callSite;
    }

    /*
    public static CallSite bootstrapSetObjectProp(MethodHandles.Lookup lookup,
                                                  String name, MethodType type) {
        CachingCallSite callSite = new CachingCallSite(lookup, type);
        MethodHandle check = SETOBJPROP.bindTo(callSite);
        check = check.asType(type);

        callSite.setTarget(check);
        return callSite;
    }
    */

/*
    public static Object callProp0(CachingCallSite callSite, Object value,
                               String property, Context cx, Scriptable scope)
            throws Throwable {
        if (value.getClass() != NativeJavaObject.class) {
            callSite.setTarget(CALLPROP0_FALLBACK);
            return CALLPROP0_FALLBACK.invoke(value, property, cx, scope);
        }

        Object javaObject = ((NativeJavaObject)value).unwrap();
        Class<?> javaClass = javaObject.getClass();
        MethodHandle target, localTarget;
        target = callSite.lookup.unreflect(javaClass.getMethod(property));
        target = localTarget = target.asType(MethodType.genericMethodType(1));
        target = MethodHandles.filterArguments(target, 0, UNWRAP);
        target = MethodHandles.dropArguments(target, 1,
                String.class, Context.class, Scriptable.class);

        MethodHandle test = CHECK_CLASS.bindTo(javaClass);
        test = test.asType(MethodType.methodType(boolean.class, Object.class));

        MethodHandle guard = MethodHandles.guardWithTest(test, target, callSite.getTarget());
        callSite.setTarget(guard);

        return localTarget.invoke(javaObject);
    }
*/
    public static Object initGetObjectProp(CachingCallSite callSite, Object value,
                                           String property, Context cx, Scriptable scope)
        throws Throwable
    {
        if (value instanceof ScriptableObject) {
            final int mapping = ((ScriptableObject)value).getMapping(property);
            if (mapping >= 0) {
                return replaceGetFastObjectProp(callSite, value, property, cx, scope, mapping);
            }
        }

        // Otherwise, always fallback to ScriptRuntime.getObjectProp
        callSite.setTarget(GETOBJPROP_FALLBACK);
        return GETOBJPROP_FALLBACK.invoke(value, property, cx, scope);
    }

    public static Object getFastObjectProp(int index, Object value, String property, Context cx, Scriptable scope)
    {
        return ((ScriptableObject)value).getMappedSlot(index, scope);
    }

    public static boolean isSameObject(Object so, Object value)
    {
        return so == value;
    }

    private static Object replaceGetFastObjectProp(CachingCallSite callSite, Object value,
                                                   String property, Context cx, Scriptable scope,
                                                   int index)
            throws Throwable
    {
        // Make a MethodHandle that can go directly to the ScriptableObject
        // First arg is an int
        MethodHandle target = MethodHandles.insertArguments(GETFASTOBJPROP, 0, index);

        // Make a "guard" MethodHandle that will see if it's the same object
        MethodHandle test = MethodHandles.insertArguments(CHECK_SAME, 0, value);

        MethodHandle guard = MethodHandles.guardWithTest(test, target, GETOBJPROP_FALLBACK);
        callSite.setTarget(guard);
        return guard.invoke(value, property, cx, scope);
    }

/*
        if (!(value instanceof ClassyScriptable)) {
            callSite.setTarget(GETOBJPROP_FALLBACK);
            return GETOBJPROP_FALLBACK.invoke(value, property, cx, scope);
        }

        ClassyScriptable classy = (ClassyScriptable) value;
        ClassyLayout layout = classy.getLayout();

        ClassyLayout.Mapping mapping = layout.findMapping(property);
        if (mapping == null) {
            callSite.setTarget(GETOBJPROP_FALLBACK);
            return GETOBJPROP_FALLBACK.invoke(value, property, cx, scope);
        }
        int offset = mapping.offset();

        MethodHandle target = MethodHandles.insertArguments(GETFASTOBJPROP, 1,
                Integer.valueOf(offset));
        target = MethodHandles.dropArguments(target, 1, String.class,
                Context.class, Scriptable.class);

        MethodHandle test = CHECK_LAYOUT.bindTo(layout);
        test = test.asType(MethodType.methodType(boolean.class, Object.class));

        MethodHandle guard = MethodHandles.guardWithTest(test, target, callSite.getTarget());
        callSite.setTarget(guard);
*/
        /* if (callSite.layout != layout) {
            ClassyLayout.Mapping mapping = layout.findMapping(property);
            if (mapping == null) {
                callSite.setTarget(GETOBJPROP_FALLBACK);
                return GETOBJPROP_FALLBACK.invoke(value, property, cx, scope);
            } else {
                callSite.layout = layout;
                callSite.offset = mapping.offset();
            }
        } */
/*
        return classy.getValueAtOffset(offset, classy);
    }

/*
    public static Object setObjectProp(CachingCallSite callSite, Object obj,
                               String property, Object value, Context cx)
            throws Throwable {
        if (!(obj instanceof ClassyScriptable)) {
            callSite.setTarget(SETOBJPROP_FALLBACK);
            return SETOBJPROP_FALLBACK.invoke(obj, property, value, cx);
        }

        ClassyScriptable classy = (ClassyScriptable) obj;
        ClassyLayout layout = classy.getLayout();
        
        Mapping mapping = layout.findMapping(property);
        int offset;
        
        if (mapping == null) {
            classy.put(property, classy, value);
            layout = classy.getLayout();
            mapping = layout.findMapping(property);
            offset = mapping.offset();
        } else {
            offset = mapping.offset();
            classy.putValueAtOffset(offset, classy, value);
        }
      
        MethodHandle target = MethodHandles.insertArguments(SETFASTOBJPROP, 1,
                Integer.valueOf(offset));
        target = MethodHandles.dropArguments(target, 1, String.class);
        target = MethodHandles.dropArguments(target, 3, Context.class);

        MethodHandle test = CHECK_LAYOUT.bindTo(layout);
        test = test.asType(MethodType.methodType(boolean.class, Object.class));

        MethodHandle guard = MethodHandles.guardWithTest(test, target, callSite.getTarget());
        callSite.setTarget(guard);
        return value;
    }
    */

    private static final MethodHandle CHECK_SAME;
    //private static final MethodHandle CHECK_LAYOUT;
    //private static final MethodHandle INITCALL;
    private static final MethodHandle INITGETOBJPROP;
    //private static final MethodHandle CALLPROP0_FALLBACK;
    private static final MethodHandle GETOBJPROP_FALLBACK;
    private static final MethodHandle GETFASTOBJPROP;
    //private static final MethodHandle UNWRAP;
    //private static final MethodHandle SETOBJPROP_FALLBACK;
    //private static final MethodHandle SETOBJPROP;
    //private static final MethodHandle SETFASTOBJPROP;

    static {
        MethodHandles.Lookup lookup = MethodHandles.lookup();
        try {
            INITGETOBJPROP = lookup.findStatic(InvokeDynamicSupport.class, "initGetObjectProp",
                    MethodType.methodType(Object.class, CachingCallSite.class,
                            Object.class, String.class, Context.class,
                            Scriptable.class));
            GETOBJPROP_FALLBACK = lookup.findStatic(ScriptRuntime.class, "getObjectProp",
                    MethodType.methodType(Object.class, Object.class,
                            String.class, Context.class, Scriptable.class));
            GETFASTOBJPROP = lookup.findStatic(InvokeDynamicSupport.class, "getFastObjectProp",
                    MethodType.methodType(Object.class, Integer.TYPE,
                            Object.class, String.class, Context.class,
                            Scriptable.class));
            CHECK_SAME = lookup.findStatic(InvokeDynamicSupport.class, "isSameObject",
                    MethodType.methodType(Boolean.TYPE, Object.class, Object.class));

        /*
            GETFASTOBJPROP = lookup.findStatic(InvokeDynamicSupport.class, "getFastObjectProp",
                    MethodType.methodType(Object.class, Integer.TYPE, Scriptable.class));
            CHECK_CLASS = lookup.findStatic(InvokeDynamicSupport.class, "checkClass",
                    MethodType.methodType(boolean.class, Class.class, Object.class));
            CHECK_LAYOUT = lookup.findStatic(InvokeDynamicSupport.class, "checkLayout",
                    MethodType.methodType(boolean.class, ClassyLayout.class, Object.class));
            CALLPROP0_FALLBACK = lookup.findStatic(OptRuntime.class, "callProp0",
                    MethodType.methodType(Object.class, Object.class,
                            String.class, Context.class, Scriptable.class));
            UNWRAP = lookup.findStatic(InvokeDynamicSupport.class, "unwrapObject",
                    MethodType.methodType(Object.class, Object.class));
            SETOBJPROP_FALLBACK = lookup.findStatic(ScriptRuntime.class, "setObjectProp",
                    MethodType.methodType(Object.class, Object.class,
                            String.class, Object.class, Context.class));
            SETOBJPROP = lookup.findStatic(InvokeDynamicSupport.class, "setObjectProp",
                    MethodType.methodType(Object.class, CachingCallSite.class,
                            Object.class, String.class, Object.class, Context.class));
            SETFASTOBJPROP = lookup.findStatic(InvokeDynamicSupport.class, "setFastObjectProp",
                    MethodType.methodType(Object.class, Object.class, Integer.TYPE, Object.class));
                    */
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
    }
}
