package org.mozilla.javascript;

import java.io.Serial;
import java.io.Serializable;

/**
 * Represents a script object built upon a {@link JSDescriptor}. This class does not support the
 * {@link Callable} interface scripts do not support arguments or some other parts of a call
 * operation.
 */
public class JSScript implements Script, ScriptOrFn<JSScript>, Serializable {
    @Serial private static final long serialVersionUID = 1L;

    private final JSDescriptor<JSScript> descriptor;
    private final transient Scriptable homeObject;

    public JSScript(JSDescriptor<JSScript> descriptor, Scriptable homeObject) {
        this.descriptor = descriptor;
        this.homeObject = homeObject;
    }

    @Override
    public JSDescriptor<JSScript> getDescriptor() {
        return descriptor;
    }

    @Override
    public Scriptable getHomeObject() {
        return homeObject;
    }

    JSCode<JSScript> getCode() {
        return descriptor.getCode();
    }

    @Override
    public Object exec(Context cx, VarScope scope, Scriptable thisObj) {
        Object ret;
        if (thisObj instanceof TopLevel) {
            thisObj = ((TopLevel) thisObj).getGlobalThis();
        }
        if (!ScriptRuntime.hasTopCall(cx)) {
            // It will go through "call" path. but they are equivalent
            ret = ScriptRuntime.doTopCall(this, cx, scope, thisObj, descriptor.isStrict());
            cx.processMicrotasks();
        } else {
            ret =
                    descriptor
                            .getCode()
                            .execute(cx, this, null, scope, thisObj, ScriptRuntime.emptyArgs);
        }
        return ret;
    }

    @Serial
    protected Object writeReplace() {
        if (descriptor.isInterpreted()) {
            return this;
        } else {
            return new CompiledScriptProxy(descriptor);
        }
    }

    /**
     * Serialization proxy for compiled scripts. On deserialization, the source is recompiled from
     * scratch rather than restoring the generated bytecode directly.
     *
     * <p><b>Advantages:</b>
     *
     * <ul>
     *   <li>Works for scripts of any complexity: nested functions, closures, regex literals,
     *       template literals, etc.
     *   <li>Cross-JVM compatible — the serialized form is plain source text.
     *   <li>Strict mode and language version are preserved and re-applied on deserialization.
     * </ul>
     *
     * <p><b>Limitations:</b>
     *
     * <ul>
     *   <li>Line numbers: the first line number is hardcoded to 1 on deserialization, so stack
     *       traces will report wrong line numbers if the original script started at a different
     *       line.
     *   <li>Security domain: the security domain from the original compilation is not preserved.
     *   <li>Compiler options: only the language version is stored; other {@link CompilerEnvirons}
     *       settings are lost.
     *   <li>Performance: deserialization triggers a full parse and compile cycle.
     * </ul>
     */
    private static final class CompiledScriptProxy implements Serializable {
        @Serial private static final long serialVersionUID = 1L;

        private final String source;
        private final String sourceName;
        private final int languageVersion;

        CompiledScriptProxy(JSDescriptor<JSScript> descriptor) {
            this.source = descriptor.getRawSource();
            this.sourceName = descriptor.getSourceName();
            this.languageVersion = descriptor.getLanguageVersion();
        }

        /** recompiles from source */
        @Serial
        private Object readResolve() {
            Context cx = Context.enter();
            try {
                cx.setLanguageVersion(languageVersion);
                cx.setInterpretedMode(false);
                return cx.compileString(source, sourceName, 1, null);
            } finally {
                Context.exit();
            }
        }
    }
}
