name: Check Test262 Properties

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  check262:
    runs-on: ubuntu-latest
    name: Check262 Tests
    steps:
    - name: Check out Rhino
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2
    - name: Check out test262
      # We don't actually want all the history for this part
      run: git submodule update --init --single-branch
    - name: Set up Java
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      # This test requires Java 11 only
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Run Check
      run: >-
        ./tools/check-test262.sh